[versions]
gson = "2.3.1"
protocol-connection = "3.0.0.Beta11-20251212.150341-16"
protocol-common = "3.0.0.Beta11-20251212.150341-15"
protocol-codec = "3.0.0.Beta11-20251212.150341-16"
mcprotocollib = "1.21.11-20251210.192611-9"
adventure = "4.25.0"
undertow = "2.3.20.Final"

[libraries]
protocol-common = { group = "org.cloudburstmc.protocol", name = "common", version.ref = "protocol-common" }
protocol-codec = { group = "org.cloudburstmc.protocol", name = "bedrock-codec", version.ref = "protocol-codec" }
protocol-connection = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version.ref = "protocol-connection" }

mcprotocollib = { group = "org.geysermc.mcprotocollib", name = "protocol", version.ref = "mcprotocollib" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
adventure-text-serializer-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }

undertow-core = { group = "io.undertow", name = "undertow-core", version.ref = "undertow" }
undertow-websockets-jsr = { group = "io.undertow", name = "undertow-websockets-jsr", version.ref = "undertow" }

[bundles]
bedrock = [ "protocol-common", "protocol-codec", "protocol-connection" ]
java = [ "mcprotocollib" ]
undertow = [ "undertow-core", "undertow-websockets-jsr" ]